### ISSUE TITLE
Not having much joy...

### ISSUE THREAD

**Issue by JontyFrancis** [timur-tabi/amazon-vine#11]
This is what I get...

H:\Downloads\amazon-vine-master\amazon-vine-master>amazon-vine.py --browser chrome
Amazon.com email address: me@gmail.com
Amazon.com password: 
Using BeautifulSoup version 4.6.0
Using mechanize version 0.3.5
Using fake_useragent version 0.1.7
Traceback (most recent call last):
  File "H:\Downloads\amazon-vine-master\amazon-vine-master\amazon-vine.py", line 457, in <module>
    br = login()
  File "H:\Downloads\amazon-vine-master\amazon-vine-master\amazon-vine.py", line 137, in login
    cj2 = getattr(browsercookie, options.browser)()
  File "C:\Python27\lib\site-packages\browsercookie\__init__.py", line 236, in chrome
    return Chrome(cookie_file).load()
  File "C:\Python27\lib\site-packages\browsercookie\__init__.py", line 72, in load
    for cookie in self.get_cookies():
  File "C:\Python27\lib\site-packages\browsercookie\__init__.py", line 121, in get_cookies
    value = self._decrypt(item[5], item[6], key=key)
  File "C:\Python27\lib\site-packages\browsercookie\__init__.py", line 154, in _decrypt
    raise BrowserCookieError('win32crypt must be available to decrypt Chrome cookie on Windows')
browsercookie.BrowserCookieError: win32crypt must be available to decrypt Chrome cookie on Windows

H:\Downloads\amazon-vine-master\amazon-vine-master>

Not sure what the problem is - I'm on Windows 7 - Any help most appreciated.

**Comment by timur-tabi** [comment]
browsercookie.BrowserCookieError: win32crypt must be available to decrypt Chrome cookie on Windows

Error message seems clear to me.  I don't really support Windows, but it looks like you need the win32crypt package, or trying use Firefox instead.

**Comment by JontyFrancis** [comment]
Thanks very much! I installed pypiwin32 and now it's running with no errors, parsing all/my, reporting # of items and waiting 10 mins, etc... So when the my Vine page changes and something new becomes available, will it send me a notification email to my Amazon email address? Or what? Much thanks!

**Comment by timur-tabi** [comment]
It will open up a browser window and load the order page for each item that is new since 10 minutes ago.
